# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  annotations:
    $patch: delete
  namespace: kong
spec:
  type: NodePort
  ports:
  - name: proxy
    port: 80
    targetPort: 8000
    nodePort: 31081
    protocol: TCP
  - name: proxy-ssl
    port: 443
    targetPort: 8443
    nodePort: 31444
    protocol: TCP
  selector:
    app: ingress-kong-dp
