---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ingress-kong
  namespace: kong
spec:
  template:
    spec:
      imagePullSecrets:
        - name: kong-enterprise-docker-secrets
      initContainers:
        - name: wait-for-migrations
          env:
            - name: KONG_LICENSE_DATA
              valueFrom:
                secretKeyRef:
                  name: kong-enterprise-license
                  key: license.json
      containers:
        - name: proxy
          env:
            - name: KONG_LICENSE_DATA
              valueFrom:
                secretKeyRef:
                  name: kong-enterprise-license
                  key: license.json
          ports:
            - containerPort: 8001
              name: admin
              protocol: TCP
            - containerPort: 8002
              name: manager
              protocol: TCP
            - containerPort: 8003
              name: portal
              protocol: TCP
        - name: ingress-controller
          env:
            - name: CONTROLLER_KONG_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kong-settings
                  key: KONG_PASSWORD