apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../kong-db

images:
  - name: kong
    newName: kong-docker-kong-enterprise-k8s.bintray.io/kong-enterprise-k8s
    newTag: 2.0.4.1-alpine

patchesStrategicMerge:
  - kong-ingress-dbless-ds.yml
  - kong-migrations-job.yml

secretGenerator:
  - name: kong-settings
    namespace: kong
    behavior: replace
    envs:
      - kong-settings.env
  - name: kong-enterprise-license
    namespace: kong
    files:
      - license.json
  - name: kong-enterprise-docker-secrets
    files:
      - .dockerconfig.json
    type: kubernetes.io/dockerconfigjson
